info:
    description: "CalendarApiBuilder REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Calendar Api Builder"
    version: v1.0
openapi: 3.0.1
paths:
  /bookings:
    get:
      summary: Get a list of bookings
      description: Retrieves a list of calendar bookings.
      operationId: getBookings
      tags:
        - Booking
      parameters:
        - name: orderDate
          in: query
          required: true
          schema:
            type: string
          description: The order date for filtering bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /add-booking:
    post:
      summary: Add a new calendar booking
      description: Creates a new calendar booking with the specified parameters.
      operationId: addBooking
      tags:
        - Booking
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
            application/xml:
              schema:
                $ref: "#/components/schemas/Booking"
      responses:
        200:
          description: "Calendar booking created successfully"
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:           
                type: string
components:
  schemas:
    Booking:
      type: object
      properties:
        startTime:
          type: string
          description: The start time of the booking
        endTime:
          type: string
          description: The end time of the booking
        dateOrder:
          type: string
          description: The order date
        vehicleId:
          type: integer
          description: The ID of the vehicle
        orderId:
          type: integer
          description: The ID of the command
        orderAdress:
          type: string
          description: The adress of the order
      required:
        - startTime
        - endTime
        - dateOrder
        - vehicleId
        - orderId
        - orderAdress