services:
  pa-liferay:
    hostname: pa-liferay
    image: liferay/dxp:2024.q4.3
    ports:
      - 8080:8080
    volumes:
      - ./liferay/files:/mnt/liferay/files
      - ./liferay/deploy:/mnt/liferay/deploy
      - pa_liferay_data:/opt/liferay/data
    depends_on:
      pa-database:
        condition: service_healthy
      pa-elasticsearch:
        condition: service_healthy
    networks:
      - pa-network

  pa-elasticsearch:
    hostname: pa-elasticsearch
    build:
      dockerfile: elasticsearch/Dockerfile
      context: .
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - pa_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - pa-network
    depends_on:
      - fixsysctl

  fixsysctl:
    restart: "no"
    privileged: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25m
    image: centos:7
    command: "sysctl -w vm.max_map_count=262144"

  pa-database:
    hostname: pa-database
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - pa_database_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - pa-network
  pa-n8n:
    hostname: pa-n8n
    image: docker.n8n.io/n8nio/n8n
    container_name: pa-n8n
    networks:
      - pa-network
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=Inetum2024
      - NODE_ENV=production
      - N8N_BASIC_AUTH_USER=demo@inetum.com
      - N8N_BASIC_AUTH_PASSWORD=Inetum2024
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - pa_n8n:/home/node/.n8n
      - ./n8n/import:/home/node/import
    post_start:
      - command: /home/node/import/import-json.sh
        privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/wget --server-response --proxy off --no-verbose --tries=1 --timeout=3 127.0.0.1:5678/healthz -O /dev/null 2>&1 | grep -q 'HTTP/1.1 200 OK'" ]
      interval: 20s
      retries: 3

volumes:
  pa_liferay_data:
  pa_elasticsearch_data:
  pa_database_data:
  pa_n8n:


networks:
  pa-network:
    name: pa-network
